### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by IvaSakharevych** [IvaSakharevych/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by IvannaSakharevych** [comment]
January 15, 2015 - August 8, 2018
Worked as a seamstress in Daniro.
https://daniro.ua/

August 9, 2018 - May 2019
She worked as a seamstress in wedding dresses.

December 2018
I moved to Lviv.

June 2019 - December 17, 2019
Seller of non-food products in Kyivstar.
https://kyivstar.ua/uk/mm

And then quarantine due to coronavirus.

September 10 - today
Worked as a product picker in Romus-Polygraph.
https://romus.ua/
